#!/system/bin/sh
#
#
#=======================================
#=======================================
# PROJECT DIRECT INJECT BY EXIT_ONLY ===
#=======================================
#=======================================
#
#

DIRECT=/data/direct_inject/S01_zipalign_apks.log;
DB=/data/direct_inject/S01_zipalign_apks.db;

busybox rm -f $DIRECT
busybox rm -f $DB

busybox touch $DIRECT
busybox touch $DB;

echo "Starting FV Automatic ZipAlign $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $DIRECT;

for DIR in /preload/app /system/app /data/app; do
	cd $DIR;
	for APK in *.apk; do
		if [ $APK -ot $DB ] && [ $(grep "$DIR/$APK" $DB|wc -l) -gt 0 ]; then
			echo "Already checked: $DIR/$APK" | tee -a $DIRECT;
		else
			ZIPCHECK=`/system/xbin/zipalign -c -v 4 $APK | grep FAILED | wc -l`;
			if [ $ZIPCHECK == "1" ]; then
				echo "Now aligning: $DIR/$APK" | tee -a $DIRECT;
				/system/xbin/zipalign -v -f 4 $APK /sdcard/download/$APK;
				busybox mount -o rw,remount /system;
				cp -f -p /sdcard/download/$APK $APK;
				grep "$DIR/$APK" $DB > /dev/null || echo $DIR/$APK >> $DB;
			else
				echo "Already aligned: $DIR/$APK" | tee -a $DIRECT;
				grep "$DIR/$APK" $DB > /dev/null || echo $DIR/$APK >> $DB;
			fi;
		fi;
	done;
done;

echo "Automatic ZipAlign finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $DIRECT;